package kr.co.isajjim.domains.furniture.domain.constant;

import com.fasterxml.jackson.annotation.JsonCreator;
import lombok.Getter;

@Getter
public enum FurnitureLabel {
    SOFA,
    SOFA_BED,
    LOVESEAT,
    FUTON,
    CHAISE_LONGUE,
    ARMCHAIR,
    CHAIR,
    ROCKING_CHAIR,
    RECLINER,
    FOLDING_CHAIR,
    DECK_CHAIR,
    HIGHCHAIR,
    STOOL,
    STEP_STOOL,
    FOOTSTOOL,
    OTTOMAN,
    BENCH,
    BED,
    BUNK_BED,
    CRIB,
    MATTRESS,
    TABLE,
    DINING_TABLE,
    COFFEE_TABLE,
    KITCHEN_TABLE,
    DESK,
    BOOKCASE,
    CUPBOARD,
    WARDROBE,
    DRESSER,
    DRAWER,
    FILE_CABINET,
    CABINET,
    ARMOIRE,
    LOCKER,
    SHELF,
    PIANO,
    HEADBOARD,
    REFRIGERATOR,
    MICROWAVE_OVEN,
    OVEN,
    STOVE,
    DISHWASHER,
    AUTOMATIC_WASHER,
    WASHER_DRYER,
    WATER_HEATER,
    AIR_CONDITIONER,
    HEATER,
    FAN,
    VACUUM_CLEANER,
    SEWING_MACHINE,
    TOASTER,
    TOASTER_OVEN,
    BLENDER,
    COFFEE_MAKER,
    FOOD_PROCESSOR,
    KETTLE,
    TEAKETTLE,
    TELEVISION_SET,
    TV,
    COMPUTER_MONITOR,
    LAPTOP_COMPUTER,
    PRINTER,
    SPEAKER_STERO_EQUIPMENT,
    STEREO_SOUND_SYSTEM,
    SUBWOOFER,
    TELEPHONE,
    CELLULAR_TELEPHONE,
    LAMP,
    TABLE_LAMP,
    CHANDELIER,
    LANTERN,
    MIRROR,
    PAINTING,
    POSTER,
    SCULPTURE,
    FIGURINE,
    CLOCK,
    WALL_CLOCK,
    VASE,
    FLOWERPOT,
    PLANT,
    TREE,
    PILLOW,
    CUSHION,
    BLANKET,
    BEDSPREAD,
    QUILT,
    CURTAIN,
    BATHTUB,
    TOILET,
    SINK,
    KITCHEN_SINK,
    WASHBASIN,
    FIREPLACE;

    @JsonCreator
    public static FurnitureLabel from(String value) {
        String normalized = value.toUpperCase()
                .replace("(", "")
                .replace(")", "");
        return FurnitureLabel.valueOf(normalized);
    }
}