# application.yml
spring:
  application:
    name: isajjim
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

rest-client:
  connect-timeout: 5
  read-timeout: 30