# application-local.yml
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/isajjim
#   url: jdbc:h2:mem:isajjim
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: ${LOCAL_REDIS_PORT}

swagger:
  server-url: http://localhost:8080

frontend:
  base-url: ${LOCAL_BASE_URL}
  main-page: ${MAIN_PAGE}
  login-fail-page: ${LOGIN_FAIL_PAGE}
  local-url: ${LOCAL_URL}
  local-secure-url: ${LOCAL_SECURE_URL}