# application.yml
spring:
  application:
    name: isajjim
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

rest-client:
  connect-timeout: 5
  read-timeout: 30

infra:
  ai:
    base-url: ${AI_BASE_URL}
    use-server: ${AI_USE_SERVER}
  google:
    project-id: ${GOOGLE_PROJECT_ID}
    gcs:
      key-path: ${GOOGLE_GCS_KEY_PATH:}
      bucket: ${GOOGLE_GCS_BUCKET}
    gemini:
      model: ${GEMINI_MODEL}

estimate:
  extra-volume-ratio: ${ESTIMATE_EXTRA_VOLUME_RATIO}