# application-dev.yml
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

swagger:
  server-url: ${DEV_SWAGGER_URL}

frontend:
  base-url: ${DEV_BASE_URL}
  main-page: ${MAIN_PAGE}
  login-fail-page: ${LOGIN_FAIL_PAGE}
  local-url: ${LOCAL_URL}
  local-secure-url: ${LOCAL_SECURE_URL}